<template>
  <div class="loadingio-spinner-blocks-6b6hr0l8zsu">
    <div class="ldio-2rjxy8kzclj">
      <div style="left: 18px; top: 18px; animation-delay: 0s"></div>
      <div style="left: 40px; top: 18px; animation-delay: 0.125s"></div>
      <div style="left: 62px; top: 18px; animation-delay: 0.25s"></div>
      <div style="left: 18px; top: 40px; animation-delay: 0.875s"></div>
      <div style="left: 62px; top: 40px; animation-delay: 0.375s"></div>
      <div style="left: 18px; top: 62px; animation-delay: 0.75s"></div>
      <div style="left: 40px; top: 62px; animation-delay: 0.625s"></div>
      <div style="left: 62px; top: 62px; animation-delay: 0.5s"></div>
    </div>
  </div>
</template>
<style type="text/css">
@keyframes ldio-2rjxy8kzclj {
  0% {
    background: rgb(var(--v-theme-primary), 0.33);
  }
  12.5% {
    background: rgb(var(--v-theme-primary), 0.33);
  }
  12.625% {
    background: rgb(var(--v-theme-primary));
  }
  100% {
    background: rgb(var(--v-theme-primary));
  }
}
.ldio-2rjxy8kzclj div {
  position: absolute;
  width: 20px;
  height: 20px;
  background: rgb(var(--v-theme-primary));
  animation: ldio-2rjxy8kzclj 1s linear infinite;
}
.loadingio-spinner-blocks-6b6hr0l8zsu {
  width: 50px;
  height: 50px;
  margin: auto;
}
.ldio-2rjxy8kzclj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.5);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-2rjxy8kzclj div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
